# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 461b9a5cae038d05a8bfda6ec4137bbb6c9f4a26c15cdc1269c69c7cc46bc88093dcbcb680d01bd6014c2cf97a397a4f69fb8660082cf04113051da7e3e99de3

test:
  secret_key_base: f5a5d0103d2e7065739f8b223341f5b991c0e2e126ce257d0d50fc8bfad3284fa13174760f0eff773b8e372e43eb1a79e086533b76041dfde62a896da0caebb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
